### ISSUE TITLE
Moving service failed - sudo error when changing output device

### ISSUE THREAD

**Issue by rudloffl** [Saiyato/volumio-squeezelite-plugin#3]
Hello,

I'm trying to change the USB output in the plugins settings, I get an error message and obviously no sound from the squeezebox.

The error is : 
    Moving service failed
    Stopping Squeezeligh failed with error
    Command failed :/bin/echo/volumio | /usr/bin/sudo -S /bin/cp/data/...
    [sudo] password for volumio: Sorry try again. [sudo]
    password for volumio: sudo: 1
    incorrect password attempt.

The material/softs are : raspberry, latest version of volumio, random USB dac, SSH password changed

Any solution to offer ?

Thanks

Larry

**Comment by Saiyato** [comment]
Hi Larry,

Yeah the problem is indeed the changed SSH password, I'm going to have to see if I can make that a setting... although I'm not too fond of storing passwords (not that I didn't do it right now, in the scripts)...

If you change the `echo volumio` in lines 272, 286, 311 and 342 to "echo YOURPASSWORD", that should solve your problem(s).

**Comment by rudloffl** [comment]
Hi Saiyato,

Thanks for the update. I will re-install volumio and try again (Impossible to roll back to the old password).

I will wait for a possible update. Thanks for your help

Larry

**Comment by Saiyato** [comment]
sudo should work fine now, no pwd needed
